// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Products were found",
            "schema": {
              "$ref": "#/definitions/ProductList"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product was found",
            "schema": {
              "$ref": "#/definitions/ProductById"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Error": {
      "properties": {
        "message": {
          "title": "Error.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    },
    "ProductList": {
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ProductList.data.[]"
          },
          "title": "ProductList.data",
          "type": "array"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductList",
      "type": "object"
    },
    "ProductById": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Product",
          "title": "ProductById.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ProductById",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};