service: product-service
frameworkVersion: '3'

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          method: get
          path: /products
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          method: get
          path: /products/{productId}
